# Generated by Django 4.1.2 on 2022-11-03 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('pradziosdata', models.DateField(max_length=100, verbose_name='Pradžios data')),
                ('pabaigosdata', models.DateField(max_length=100, verbose_name='Pabaigos data')),
                ('klientas1', models.CharField(max_length=100, verbose_name='Klientas')),
                ('darbuotojai', models.CharField(max_length=100, verbose_name='Darbuotojai')),
                ('darbai', models.CharField(max_length=200, verbose_name='Darbai')),
                ('saskaitos', models.CharField(max_length=100, verbose_name='Sąskaitos')),
                ('statusas', models.CharField(choices=[('v', 'Vykdomas'), ('b', 'Baigtas vykdyti')], default='v', help_text='Statusas', max_length=1)),
                ('vadovas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projektas',
                'verbose_name_plural': 'Projektai',
            },
        ),
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Išrašymo data')),
                ('suma', models.FloatField(max_length=100, verbose_name='Suma')),
                ('saskaitos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.projektas')),
            ],
            options={
                'verbose_name': 'Sąskaita',
                'verbose_name_plural': 'Sąskaitos',
            },
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardaspavarde', models.CharField(max_length=100, verbose_name='Vardas Pavardė')),
                ('imone', models.CharField(max_length=100, verbose_name='Įmonė')),
                ('kontaktai', models.CharField(max_length=100, verbose_name='Kontaktai')),
                ('klientas1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.projektas')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
            },
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardaspavarde2', models.CharField(max_length=100, verbose_name='Vardas Pavardė')),
                ('pareigos', models.CharField(max_length=100, verbose_name='Pareigos')),
                ('darbuotojai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.projektas')),
            ],
            options={
                'verbose_name': 'Darbuotojas',
                'verbose_name_plural': 'Darbuotojai',
            },
        ),
        migrations.CreateModel(
            name='Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas2', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('pastabos', models.CharField(max_length=100, verbose_name='Pastabos')),
                ('darbai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.projektas')),
            ],
            options={
                'verbose_name': 'Darbas',
                'verbose_name_plural': 'Ateityje vykdomi darbai',
            },
        ),
    ]
